config/routes.rb
EventBot::Application.routes.draw do
  resources :event_sources
  resources :events do
    member do
      post :approve
      post :reject
      get :preview_json
    end
  end

  get :process_events, to: 'main#process_events'
  root to: 'main#index'
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :venue_id, :event_source_id, :title, :location, :start_date, :date_time_string, :description, :subtitle, :category, :image_urls, :keywords, :event_url, :ticket_url, :media_url, :price, :edited, :processed, :posted

  serialize :image_urls, Array
  serialize :keywords, Array

  belongs_to :event_source

  scope :unprocessed, where(processed: false)
end

app/models/event_source.rb
class EventSource < ActiveRecord::Base
  before_create :set_scrape_date
  after_initialize :set_url_param_defaults
  before_validation :add_url_protocol

  URL_PARAM_DEFAULTS = {
    PAGE_NUMBER: 5
  }

  CATEGORIES = {
    'Active' => 'Active',
    'Arts' => 'Arts',
    'Community' => 'Community',
    'Food' => 'Food',
    'Film' => 'Film',
    'Learning' => 'Learning',
    'Music' => 'Music',
    'Performances' => 'Performances',
    'Professional' => 'Professional',
    'General' => 'General'
  }

  REGIONS = {
    'SanFranciscoCa' => 'San Francisco, CA'
  }

  attr_accessible :venue_id, :title, :region, :category, :url, :url_params, :last_scraped, :event_link_selector, :title_selector, :description_selector, :location_selector, :date_selector, :time_selector, :ticket_url_selector, :disabled
  store :css_mappers, accessors: [:event_link_selector, :title_selector, :description_selector, :location_selector, :date_selector, :time_selector, :ticket_url_selector]
  serialize :url_params, HashWithIndifferentAccess

  validates :title, presence: :true
  validates :region, presence: :true
  validates :url, presence: :true
  validates :event_link_selector, presence: :true
  # validates :title_selector, presence: :true
  # validates :location_selector, presence: :true
  # validates :date_selector, presence: :true

  has_many :events

  scope :active, where(disabled: false)

  private

  def set_scrape_date
    self.last_scraped = Time.now
  end

  def add_url_protocol
    unless self.url[/^http:\/\//] || self.url[/^https:\/\//]
      self.url = 'http://' + self.url
    end
  end

  def set_url_param_defaults
    URL_PARAM_DEFAULTS.each do |key, value|
      self.url_params[key] = value if self.url_params[key].nil?
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/event_sources_controller.rb
class EventSourcesController < ApplicationController
  before_filter :get_source, only: [:show, :edit, :update, :destroy]

  def show
    sources = EventSource.active.order(:title)
    @source_options = EventSource.active.order(:title).map do |source|
      [
        source.id,
        "#{source.title} (#{source.events.unprocessed.count} active events)"
      ]
    end

    @selected_source = sources.find_by_id(params[:id]) || sources.first
    @events =  @selected_source.events.where(processed: false).order(:created_at)
  end

  def new
    @source = EventSource.new
    @regions = EventSource::REGIONS.map { |k,v| [k.to_s.camelize, v] }
  end

  def create
    @source = EventSource.new(params[:event_source])

    if @source.save
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @regions = EventSource::REGIONS.map { |k,v| [k.to_s.camelize, v] }
  end

  def update
    @source.update_attributes(params[:event_source])
    @source.update_attributes(url_params: @source.url_params.merge(params[:url_params]))

    redirect_to root_url, notice: 'This source has been updated'
  end

  def destroy
    @source.update_attributes(disabled: true)
    redirect_to root_url, notice: 'This source has been disabled'
  end

  private

  def get_source
    @source = EventSource.find(params[:id])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :get_event, only: [:edit, :update, :approve, :reject]

  def edit

  end

  def update
    @event.update_attributes(params[:event].merge(edited: true))

    unless params[:post_event] == 'false'
      @event.update_attributes(
        processed: true,
        posted: true
      )

      event_hash = {
        event_source_id: @event.event_source_id,
        venue_id: @event.venue_id,
        title: @event.title,
        subtitle: @event.subtitle,
        description: @event.description,
        location: @event.location,
        start_time: @event.start_date,
        price: @event.price,
        image_link: @event.media_url,
        ticket_link: @event.ticket_url,
        link: @event.event_url,
        category: @event.category,
        keywords: @event.keywords[0..4].sort { |k1, k2| k1['score'] <=> k2['score'] }.reverse.map { |k| k['name'] }.join(', '),
        image_urls: @event.image_urls.map { |i| i['url'] }.join(', ')
      }

      Curl.post('http://applebutter.me/event-bot-posting/', event_hash)

      redirect_to root_url, notice: 'This event has been posted to AppleButter'
    else
      redirect_to root_url, notice: 'This event has been updated'
    end
  end

  def reject
    @event.update_attributes(
      processed: true,
      posted: false
    )

    redirect_to root_url, notice: 'This event has been rejected'
  end

  def preview_json
    event = Event.find_by_id(params[:id])
    render partial: 'events/event', locals: { event: event }
  end

  private

  def get_event
    @event = Event.find_by_id(params[:id])
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def index
    @categories = EventSource::CATEGORIES.map { |k,v| [k.to_s.camelize, v] }
    @selected_category = @categories.select { |category| category[0] == params[:category] }[0] || ''

    @sources = EventSource.active.order(:title)

    unless params[:category].nil?
      @sources = @sources.where(category: params[:category])
    end

    @regions = EventSource::REGIONS.map { |k,v| [k.to_s.camelize, v] }
    @selected_region = @regions.select { |region| region == params[:region] }[0] || @regions.first
  end

  def process_events
    EventScraper.get_yo_scrape_on EventSource.active

    redirect_to root_url, notice: 'Done'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_sources_helper.rb
module EventSourcesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/event_sources/_form.html.erb
<% if @source.errors.any? %>
  <div id="errorExplanation">
    <h4><%= pluralize(@source.errors.count, "error") %> prohibited this source from being saved:</h4>
    <ul>
    <% @source.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<div class="control-group">
  <%= f.label :title, class: "control-label" %>
  <div class="controls">
    <%= f.text_field :title, :class => 'span6' %>
  </div>
</div>
<div class="control-group">
  <%= f.label :region, class: "control-label" %>
  <div class="controls">
    <%= f.select :region, options_from_collection_for_select(@regions, :first, :last), :class => 'span6' %>
  </div>
</div>
<div class="control-group">
  <%= f.label :venue_id, class: "control-label" %>
  <div class="controls">
    <%= f.text_field :venue_id, :class => 'span6' %>
    <span class="help-block">Add a venue's ID from AppleButter to associate events with a specific venue.</span>
  </div>
</div>
<hr />
<div class="control-group">
  <%= f.label :url, class: "control-label" %>
  <div class="controls">
    <%= f.text_field :url, :class => 'span6' %>
  </div>
</div>
<% @source.url_params.each do |key, value| %>
  <div class="control-group">
    <%= label_tag key, "Value for #{key}", class: "control-label" %>
    <div class="controls">
      <%= text_field_tag key, value, class: 'span6', name: "url_params[#{key}]" %>
    </div>
  </div>
<% end %>
<hr />
<div class="control-group">
  <%= f.label :event_link_selector, class: "control-label" %>
  <div class="controls">
    <%= f.text_field :event_link_selector, :class => 'span6' %>
  </div>
</div>
<div class="control-group">
  <%= f.label :title_selector, class: "control-label" %>
  <div class="controls">
    <%= f.text_field :title_selector, :class => 'span6' %>
  </div>
</div>
<div class="control-group">
  <%= f.label :description_selector, class: "control-label" %>
  <div class="controls">
    <%= f.text_field :description_selector, :class => 'span6' %>
  </div>
</div>
<div class="control-group">
  <%= f.label :location_selector, class: "control-label" %>
  <div class="controls">
    <%= f.text_field :location_selector, :class => 'span6' %>
  </div>
</div>
<div class="control-group">
  <%= f.label :date_selector, class: "control-label" %>
  <div class="controls">
    <%= f.text_field :date_selector, :class => 'span6' %>
  </div>
</div>
<div class="control-group">
  <%= f.label :time_selector, class: "control-label" %>
  <div class="controls">
    <%= f.text_field :time_selector, :class => 'span6' %>
    <span class="help-block">Use this if event date and time are displayed in different tags.</span>
  </div>
</div>
<div class="control-group">
  <%= f.label :ticket_url_selector, class: "control-label" %>
  <div class="controls">
    <%= f.text_field :ticket_url_selector, :class => 'span6' %>
  </div>
</div>

app/views/event_sources/edit.html.erb
<%= form_for @source, html: { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend>Update This Event Source</legend>
    <%= render partial: 'event_sources/form', locals: { f: f }  %>
    <div class="form-actions">
      <%= link_to 'Cancel', root_url %>
      <%= f.submit 'Save Changes', :class => 'btn btn-primary' %>
    </div>
  </fieldset>
<% end %>

app/views/event_sources/new.html.erb
<%= form_for @source, html: { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend>Create a New Event Source</legend>
    <%= render partial: 'event_sources/form', locals: { f: f }  %>
    <div class="form-actions">
      <%= link_to 'Cancel', root_url %>
      <%= f.submit 'Save Changes', :class => 'btn btn-primary' %>
    </div>
  </fieldset>
<% end %>

app/views/event_sources/show.html.erb
<% if @source_options.length > 0 %>
  <h3>
    Events for <%= @selected_source.title %> <small><%= pluralize(@events.count, "event") %> found // Last scraped <%= @selected_source.last_scraped.strftime("%B %d, %Y at %l:%M %p") %></small>
  </h3>
  <div class="pull-right btn-toolbar filters">
    <%= select_tag :source, options_from_collection_for_select(@source_options, :first, :last, selected: @selected_source.id), :class => 'pull-right' %>
  </div>
  <div id="events_outer">
    <% if @events.length == 0 %>
      <strong>No scraped events for "<%= @selected_source.title %>"</strong>
    <% else %>
      <table class="table table-condensed">
        <thead>
          <tr>
            <th>Title</th>
            <th>Date</th>
            <th>Location</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @events.each do |e| %>
            <tr>
              <td class="event-title span6">
                <a class="preview-event" href="<%= e.event_url %>"><%= e.title %></a>
              </td>
              <td>
                <%= e.date_time_string %>
              </td>
              <td>
                <%= e.location %>
              </td>
              <td style="text-align:right;">
                <%= link_to 'Edit/Post Event', edit_event_url(e), :class => 'btn btn-primary' %>
                <%= link_to 'Reject Event', reject_event_url(e), method: :post, :class => 'btn btn-danger' %>
              </td>
            </tr>
            <tr class="separator">
              <td colspan="1">
                <strong>Tags:</strong>
                <% if e.keywords.length > 0 %>
                  <ul class="tag-list unstyled">
                    <% e.keywords.sort { |kw1, kw2| kw1["score"] <=> kw2["score"] }.reverse.each do |kw| %>
                      <li><%= kw["name"] %></li>
                    <% end %>
                  </ul>
                <% else %>
                  <span>No relevant keywords found</span>
                <% end %>
              </td>
              <td colspan="3">
                <strong>Images:</strong>
                <ul class="image-list unstyled">
                  <% e.image_urls[0..1].each do |image| %>
                    <li><%= image_tag image["url"], size: '100x100' %></li>
                  <% end %>
                </ul>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
  <div id="page_preview_modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      <h3 id="myModalLabel">Event Preview</h3>
    </div>
    <div class="modal-body">
      <iframe id="page_preview_frame" width="840" height="600"></iframe>
    </div>
    <div class="modal-footer">
      <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    </div>
  </div>
<% else %>
  <div class="container">
    <strong>You haven't set up any sources. <%= link_to 'Add New Source', new_event_source_url %></strong>
  </div>
<% end %>

app/views/events/_form.html.erb
<% if @event.edited %>
  <div class="alert alert-warning">
    This event has been edited.
  </div>
<% end %>
<% if @event.errors.any? %>
  <div class="alert alert-error">
    <h4><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h4>
    <ul>
    <% @event.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<div class="control-group">
  <%= f.label :title, class: "control-label" %>
  <div class="controls">
    <%= f.text_field :title, :class => 'span6' %>
  </div>
</div>
<div class="control-group">
  <%= f.label :subtitle, class: "control-label" %>
  <div class="controls">
    <%= f.text_field :subtitle, :class => 'span6' %>
  </div>
</div>
<div class="control-group">
  <%= f.label :category, class: "control-label" %>
  <div class="controls">
    <%= f.text_field :category, :class => 'span6' %>
  </div>
</div>
<div class="control-group">
  <%= f.label :start_date, "Start date/time", class: "control-label" %>
  <div class="controls">
    <%= f.datetime_select :start_date, :class => 'span6', :ampm => true, :start_year => Time.now.year, :minute_step => 15 %>
    <br />
    <span class="text-warning">The scraped date was "<%= @event.date_time_string %>"</span>
  </div>
</div>
<div class="control-group">
  <%= f.label :description, class: "control-label" %>
  <div class="controls">
    <%= f.text_area :description, rows: 7, :class => 'span6' %>
  </div>
</div>
<div class="control-group">
  <%= f.label :price, class: "control-label" %>
  <div class="controls">
    <%= f.text_field :price, :class => 'span6' %>
  </div>
</div>
<div class="control-group">
  <%= f.label :event_url, class: "control-label" %>
  <div class="controls">
    <%= f.text_field :event_url, :class => 'span6' %>
  </div>
</div>
<div class="control-group">
  <%= f.label :ticket_url, class: "control-label" %>
  <div class="controls">
    <%= f.text_field :ticket_url, :class => 'span6' %>
  </div>
</div>
<div class="control-group">
  <%= f.label :media_url, "Image Url", class: "control-label" %>
  <div class="controls">
    <%= f.text_field :media_url, :class => 'span6' %>
  </div>
</div>
<input type="hidden" id="post_event" name="post_event" value="false">

app/views/events/edit.html.erb
<% content_for :nav do %>
  <%= link_to 'Back to Events', event_source_url(@event.event_source_id), :class => 'admin-link' %>
<% end %>
<% if @event.processed %>
  <div class="alert alert-error">
    This event has been processed and cannot be edited.
  </div>
<% else %>
  <%= link_to 'Reject Event', reject_event_url(@event), method: :post, :class => 'btn btn-danger pull-right' %>
  <%= form_for @event, html: { :class => 'form-horizontal' } do |f| %>
    <fieldset>
      <legend>Edit This Event <small>Scraped <%= @event.created_at.strftime("%B %d, %Y at %l:%M %p") %> from &quot;<%= @event.event_source.title %>&quot;</small></legend>
      <%= render partial: 'events/form', locals: { f: f }  %>
      <div class="form-actions">
        <%= link_to 'Cancel', root_url %>
        <%= f.submit 'Save Changes', :class => 'btn btn-primary' %>
        <%= f.submit 'Save & Post to AppleButter', :class => 'btn btn-warning', name: 'post_event' %>
      </div>
    </fieldset>
  <% end %>
<% end %>

app/views/events/new.html.erb
<% content_for :nav do %>
  <%= link_to 'Back to Events', root_url, :class => 'admin-link' %>
<% end %>
<%= form_for @event, html: { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend>Create a New Event</legend>
    <%= render partial: 'events/form', locals: { f: f }  %>
    <div class="form-actions">
      <%= link_to 'Cancel', root_url %>
      <%= f.submit 'Save Changes', :class => 'btn btn-primary' %>
    </div>
  </fieldset>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EventBot</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="body_container" class="container">
    <div id="nav_container">
      <%= link_to root_url do %>
        <i class="icon-home icon-2x"></i>
      <% end %>
      <%= yield :nav %>
      <%= link_to 'Scrape Events', process_events_url, :class => 'btn btn-warning pull-right', confirm: 'This could take several minutes and may time out. Do you wish to proceed?' %>
    </div>
    <!-- <div class="alert alert-error">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <strong><%= flash[:notice] %></strong>
    </div> -->
    <div class="well">
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/main/index.html.erb
<% content_for :nav do %>
  <%= link_to 'Add New Source', new_event_source_url, :class => 'admin-link' %>
<% end %>
<section>
  <h3>Event Sources</h3>
  <div class="pull-right btn-toolbar filters">
    <h4>Filter by Category</h4>
    <%= select_tag :category, options_from_collection_for_select(@categories, :first, :last, selected: @selected_category[0]), include_blank: true %>
    <% select_tag :region, options_from_collection_for_select(@regions, :first, :last, selected: @selected_region[0]) %>
  </div>
</section>
<% if @sources.length == 0 %>
  <strong>No sources found</strong>
<% else %>
  <table class="table" class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>Title</th>
        <th>Region</th>
        <th>Category</th>
        <th class="center">Active Events</th>
        <th>Last Scraped</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @sources.each do |source| %>
        <tr>
          <td class="span3">
            <strong>
              <%= link_to source.title, event_source_path(source) %>
            </strong>
          </td>
          <td class="span2">
            <%= EventSource::REGIONS[source.region] %>
          </td>
          <td class="span2">
            <%= EventSource::CATEGORIES[source.category] %>
          </td>
          <td class="center span2">
            <%= source.events.unprocessed.count %>
          </td>
          <td class="span3">
            <%= source.last_scraped.strftime("%m/%d/%Y at %l:%M %p") %>
          </td>
          <td class="span2">
            <a class="hidden scrape-link btn">Scrape Site</a>
            <%= link_to 'Edit', edit_event_source_url(source), :class => 'btn btn-primary' %>
            <%= link_to 'Disable', source, confirm: 'Are you sure you want to disable this source?', method: :delete, :class => 'btn btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>